[tool.poetry]
name = "confirming-api"
version = "0.1.0"
description = "Confirming API Rest"
authors = ["Klimb <klimb@klimb.pe>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
